- name: VyOS configuration
  hosts: router_main
  gather_facts: false
  tasks:
    - name: setup config
      vyos.vyos.vyos_config:
        match: "none"
        lines:

          # SET SSH KEY
          # FIXME: should probably store this in a file for use in other modules.
          - set system login user 'vyos' authentication public-keys 'bender' key "AAAAC3NzaC1lZDI1NTE5AAAAIMztLpThvXPu85+kGuD/OVdpUNAXbPpYtcPUIyU96PU1"
          - set system login user 'vyos' authentication public-keys 'bender' type "ssh-ed25519"

          # CONFIGURE INTERFACES
          - set interface ethernet 'eth0' description 'WAN'
          - set interface ethernet 'eth0' address dhcp
          - set interface ethernet 'eth1' description 'LAN'
          - set interface ethernet 'eth1' address '192.168.2.1/24'
          - set service ssh port '22'

          # CONFIGURE DHCP
          - set service dhcp-server shared-network-name 'LAN' subnet '192.168.2.0/24' default-router '192.168.2.1'
          - set service dhcp-server shared-network-name 'LAN' subnet '192.168.2.0/24' name-server '192.168.2.1'
          - set service dhcp-server shared-network-name 'LAN' subnet '192.168.2.0/24' domain-name 'arvinderd.com'
          - set service dhcp-server shared-network-name 'LAN' subnet '192.168.2.0/24' lease '86400'
          - set service dhcp-server shared-network-name 'LAN' subnet '192.168.2.0/24' range 0 start '192.168.2.2'
          - set service dhcp-server shared-network-name 'LAN' subnet '192.168.2.0/24' range 0 stop '192.168.2.100'
          # CONFIGURE DNS
          - set service dns forwarding cache-size '0'
          - set service dns forwarding listen-address '192.168.2.1'
          - set service dns forwarding allow-from '192.168.2.0/24'

          #CONFIGURE NAT (sad boy hours)
          - set nat source rule '100' outbound-interface 'eth0'
          - set nat source rule '100' source address '192.168.2.0/24'
          - set nat source rule '100' translation address masquerade
        save: true
