apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: local-path-provisioner
  namespace: storage-system
spec:
  interval: 15m
  url: https://github.com/rancher/local-path-provisioner
  ref:
    branch: master
