apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-storage-provisioner
  namespace: storage-system
  labels:
    reconcile.fluxcd.io/watch: Enabled
spec:
  chart:
    spec:
      chart: ./deploy/chart/local-path-provisioner
      version: 0.0.32
      sourceRef:
        kind: GitRepository
        name: local-storage-provisioner
        namespace: storage-system
  values:
    storageClass:
      create: true
      reclaimPolicy: Delete
      defaultClass: true
      defaultVolumeType: local
      pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}/"
    nodePathMap:
      - {"node": "DEFAULT_PATH_FOR_NON_LISTED_NODES", "paths": ["/persist/k3s/data"] }
  interval: 15m
  timeout: 5m
  releaseName: local-path-storage
